language: go

go:
  - "1.11.x"
  - "1.x"

os:
  - linux
  - osx
  - windows

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
